[package]
name = "position-aircraft-native"
version = "0.4.0"
edition.workspace = true
license.workspace = true
description = "Native X-Plane 12 PositionAircraft replacement"

[lib]
crate-type = ["cdylib"]

[dependencies]
egui.workspace = true
egui_glow.workspace = true
windows-sys.workspace = true
xplane-airports.workspace = true
xplane-plugin.workspace = true
xplane-sdk-sys.workspace = true
