use xplane_plugin::DataRef;

pub(in crate::runtime) struct DataRefs {
    pub(in crate::runtime) latitude: DataRef,
    pub(in crate::runtime) longitude: DataRef,
    pub(in crate::runtime) elevation: DataRef,
    pub(in crate::runtime) theta: DataRef,
    pub(in crate::runtime) phi: DataRef,
    pub(in crate::runtime) psi: DataRef,
    pub(in crate::runtime) magvar: DataRef,
    pub(in crate::runtime) ias: DataRef,
    pub(in crate::runtime) local_x: DataRef,
    pub(in crate::runtime) local_y: DataRef,
    pub(in crate::runtime) local_z: DataRef,
    pub(in crate::runtime) local_vx: DataRef,
    pub(in crate::runtime) local_vy: DataRef,
    pub(in crate::runtime) local_vz: DataRef,
    pub(in crate::runtime) rate_p: DataRef,
    pub(in crate::runtime) rate_q: DataRef,
    pub(in crate::runtime) rate_r: DataRef,
    pub(in crate::runtime) quaternion: DataRef,
    pub(in crate::runtime) throttles: DataRef,
    pub(in crate::runtime) flaps: DataRef,
    pub(in crate::runtime) gear: DataRef,
    pub(in crate::runtime) ap_mode: DataRef,
    pub(in crate::runtime) ap_altitude: DataRef,
    pub(in crate::runtime) ap_vvi: DataRef,
    pub(in crate::runtime) ap_heading: DataRef,
    pub(in crate::runtime) ap_airspeed: DataRef,
    pub(in crate::runtime) ap_state: DataRef,
    pub(in crate::runtime) ap_heading_roll_mode: DataRef,
    pub(in crate::runtime) vr_enabled: DataRef,
    pub(in crate::runtime) projection_matrix: DataRef,
    pub(in crate::runtime) modelview_matrix: DataRef,
    pub(in crate::runtime) viewport: DataRef,
}

impl DataRefs {
    pub(super) fn find() -> Result<Self, String> {
        Ok(Self {
            latitude: DataRef::required("sim/flightmodel/position/latitude")?,
            longitude: DataRef::required("sim/flightmodel/position/longitude")?,
            elevation: DataRef::required("sim/flightmodel/position/elevation")?,
            theta: DataRef::required("sim/flightmodel/position/theta")?,
            phi: DataRef::required("sim/flightmodel/position/phi")?,
            psi: DataRef::required("sim/flightmodel/position/psi")?,
            magvar: DataRef::required("sim/flightmodel/position/magnetic_variation")?,
            ias: DataRef::required("sim/flightmodel/position/indicated_airspeed")?,
            local_x: DataRef::required("sim/flightmodel/position/local_x")?,
            local_y: DataRef::required("sim/flightmodel/position/local_y")?,
            local_z: DataRef::required("sim/flightmodel/position/local_z")?,
            local_vx: DataRef::required("sim/flightmodel/position/local_vx")?,
            local_vy: DataRef::required("sim/flightmodel/position/local_vy")?,
            local_vz: DataRef::required("sim/flightmodel/position/local_vz")?,
            rate_p: DataRef::required("sim/flightmodel/position/P")?,
            rate_q: DataRef::required("sim/flightmodel/position/Q")?,
            rate_r: DataRef::required("sim/flightmodel/position/R")?,
            quaternion: DataRef::required("sim/flightmodel/position/q")?,
            throttles: DataRef::required("sim/flightmodel/engine/ENGN_thro")?,
            flaps: DataRef::required("sim/flightmodel/controls/flaprqst")?,
            gear: DataRef::required("sim/cockpit/switches/gear_handle_status")?,
            ap_mode: DataRef::required("sim/cockpit/autopilot/autopilot_mode")?,
            ap_altitude: DataRef::required("sim/cockpit/autopilot/altitude")?,
            ap_vvi: DataRef::required("sim/cockpit/autopilot/vertical_velocity")?,
            ap_heading: DataRef::required("sim/cockpit/autopilot/heading_mag")?,
            ap_airspeed: DataRef::required("sim/cockpit/autopilot/airspeed")?,
            ap_state: DataRef::required("sim/cockpit/autopilot/autopilot_state")?,
            ap_heading_roll_mode: DataRef::required("sim/cockpit/autopilot/heading_roll_mode")?,
            vr_enabled: DataRef::required("sim/graphics/VR/enabled")?,
            projection_matrix: DataRef::required("sim/graphics/view/projection_matrix")?,
            modelview_matrix: DataRef::required("sim/graphics/view/modelview_matrix")?,
            viewport: DataRef::required("sim/graphics/view/viewport")?,
        })
    }
}
