[package]
name = "poweroff180-hud"
version = "0.5.0"
edition.workspace = true
license.workspace = true
[lib]
name = "poweroff180_hud"
crate-type = ["cdylib", "rlib"]
[dependencies]
poweroff180 = { path = "../../crates/poweroff180" }
xplane-plugin.workspace = true
xplane-sdk-sys.workspace = true
windows-sys = { workspace = true, features = ["Win32_Graphics_Gdi", "Win32_Graphics_OpenGL"] }
