//! The plugin's only OpenGL boundary. Called exclusively by X-Plane's draw
//! callback, with a current compatibility context supplied by its GL bridge.
use crate::{
    config::Optics,
    math::View,
    runway::CameraProjection,
    scene::{Scene, Segment},
};
use windows_sys::Win32::Graphics::OpenGL::*;
use xplane_plugin::opengl::{AttributeGuard, MatrixGuard};

pub fn clear_panel(optics: Optics) {
    xplane_plugin::set_graphics_state(false);
    // SAFETY: the SDK has made the panel GL context current. No pointers escape,
    // and the enable attributes changed here are restored before returning.
    unsafe {
        let _attributes = AttributeGuard::push(GL_ENABLE_BIT);
        glDisable(GL_SCISSOR_TEST);
        glDisable(GL_STENCIL_TEST);
        glDisable(GL_CULL_FACE);
        for i in 0..6 {
            glDisable(GL_CLIP_PLANE0 + i);
        }
        glColor4f(0.0, 0.0, 0.0, 0.0);
        let (l, b, s) = (optics.panel_left, optics.panel_bottom, optics.panel_size);
        glBegin(GL_QUADS);
        glVertex2d(l, b);
        glVertex2d(l + s, b);
        glVertex2d(l + s, b + s);
        glVertex2d(l, b + s);
        glEnd();
    }
}

pub fn paint(
    scene: &Scene,
    optics: Optics,
    camera: View,
    runway_camera: Option<&CameraProjection>,
    panel: bool,
    size: (i32, i32),
    brightness: f32,
) {
    let (w, h) = size;
    let scale = f64::from(h) / 1080.0;
    xplane_plugin::set_graphics_state(true);
    // SAFETY: X-Plane owns the active GL context. The SDK state setup above and
    // balanced matrix/attribute stacks reproduce the native release-142 pass.
    // Every vertex is a finite, clipped value generated by the pure scene code.
    unsafe {
        let _attributes = AttributeGuard::push(GL_CURRENT_BIT | GL_SCISSOR_BIT | GL_ENABLE_BIT);
        glDisable(GL_CULL_FACE);
        for i in 0..6 {
            glDisable(GL_CLIP_PLANE0 + i);
        }
        glDisable(GL_ALPHA_TEST);
        glDisable(GL_STENCIL_TEST);
        let _projection = MatrixGuard::projection();
        if !panel {
            glLoadIdentity();
            glOrtho(0.0, f64::from(w), 0.0, f64::from(h), -1.0, 1.0);
        }
        let _modelview = MatrixGuard::modelview();
        if panel {
            glDisable(GL_SCISSOR_TEST);
            glTranslated(
                optics.panel_left,
                optics.panel_bottom + optics.panel_size,
                0.0,
            );
            glScaled(optics.panel_size / 960.0, -optics.panel_size / 960.0, 1.0);
            glTranslated(-480.0, -100.0, 0.0);
        } else {
            glLoadIdentity();
            glTranslated((f64::from(w) - 1920.0 * scale) / 2.0, f64::from(h), 0.0);
            glScaled(scale, -scale, 1.0);
            glEnable(GL_SCISSOR_TEST);
        }
        let mut viewport = [0; 4];
        glGetIntegerv(GL_VIEWPORT, viewport.as_mut_ptr());
        if !panel {
            glScissor(viewport[0], viewport[1], viewport[2], viewport[3]);
        }
        if panel {
            glDisable(GL_BLEND);
        }
        for (group, segments, conformal) in std::iter::once((0, &scene.conformal, true)).chain(
            scene
                .layers
                .iter()
                .enumerate()
                .map(|(group, segments)| (group, segments, false)),
        ) {
            for pass in 0..2 {
                if panel && pass == 0 {
                    continue;
                }
                if pass != 0 {
                    glColor4f(
                        if panel { 0.25 * brightness } else { 0.74 },
                        if panel { brightness } else { 0.84 },
                        if panel { 0.40 * brightness } else { 0.64 },
                        brightness,
                    );
                } else {
                    glColor4f(0.025, 0.045, 0.015, brightness * 0.32);
                }
                glBegin(GL_QUADS);
                for &segment in segments {
                    let Some(mut segment) = segment.clipped(
                        482.0,
                        102.0,
                        1438.0,
                        if group == 0 { 835.0 } else { 1005.0 },
                    ) else {
                        continue;
                    };
                    if !panel {
                        if conformal {
                            let Some((a, b)) = runway_camera.and_then(|camera| {
                                camera
                                    .point(optics, segment.a)
                                    .zip(camera.point(optics, segment.b))
                            }) else {
                                continue;
                            };
                            segment = Segment { a, b };
                        } else {
                            let a = scene.body.camera_point(camera, segment.a);
                            let b = scene.body.camera_point(camera, segment.b);
                            if a.limited || b.limited {
                                continue;
                            }
                            segment = Segment { a: a.p, b: b.p };
                        }
                    }
                    if let Some(points) = segment.quad(if pass != 0 {
                        if panel {
                            4.6
                        } else {
                            2.1
                        }
                    } else {
                        3.2
                    }) {
                        for p in points {
                            glVertex2d(p.x, p.y);
                        }
                    }
                }
                glEnd();
            }
        }
    }
}
